---
apiVersion: v1
kind: Service
metadata:
  name: video-website-extract-img-s
  labels:
    app: video-website-extract-img-s
spec:
  selector:
    app: video-website-extract-img-d
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: video-website-extract-img-d
spec:
  selector:
    matchLabels:
      app: video-website-extract-img-d
  replicas: 1
  template:
    metadata:
      labels:
        app: video-website-extract-img-d
    spec:
      containers:
      - name: video-website-extract-img-d
        image: gcr.io/cc-isv/extract-img:v3
        ports:
        - containerPort: 5000
